#!/bin/bash -x
cp params.icorrk params.i

make

PRUNDIR='Planet_Run_CK'
rm -r $PRUNDIR
mkdir $PRUNDIR
cp 1DRT $PRUNDIR
cp fort.7corrk $PRUNDIR/fort.7
cd $PRUNDIR
#(time ./igcm3_nopg) 2> runtime.txt
./1DRT
cd ..
